Get initial container env vars from host env vars

diff --git a/t3 b/t3
--- a/t3
+++ b/t3
@@ -174,7 +174,7 @@ mount_volume() {
             || usage "Volume '$1' not found"
 
         # Acquire sudo authorization for what follows
-        sudo --prompt "sudo authorization is required for bind-mounting: " --validate
+        sudo --prompt "sudo authorization is required for bind-mounting a working directory: " --validate
 
         # Determine UID and GID of the volume owner
         # (options differ between Linux and BSD)
@@ -220,7 +220,7 @@ unmount_volume() {
     # Find the directory bind-mounted to the container volume mountpoint
     RE='^/.+( +[0-9]+){4}% +(/.+)$'
     if LINE=$(df -P -l | grep --fixed-string "$VOL_MP ") && [[ "$LINE" =~ $RE ]]; then
-        sudo --prompt 'sudo authorization is required for unmounting: ' \
+        sudo --prompt 'sudo authorization is required for unmounting a working directory: ' \
             umount "${BASH_REMATCH[2]}" \
         && echo "Working directory '${BASH_REMATCH[2]}' unmounted from volume '$1'"    
     fi
@@ -763,6 +763,17 @@ if is_path "$DB_DATA"; then
     DB_DATA=$(basename "$DB_DATA")
 fi
 
+# Initialize container environment variable values
+RE='^T3_(TIMEZONE|MODE|COMPOSER_EXCLUDE|PHP_.+|php_.+)=(.*)$'
+ENV_OPTIONS=
+
+while read -r ENV_VAR; do
+    if [[ "$ENV_VAR" =~ $RE ]]; then
+        ENV_OPTIONS="$ENV_OPTIONS \
+            --env ${BASH_REMATCH[1]}=${BASH_REMATCH[2]}"
+    fi
+done <<< "$(printenv)"
+
 # Database type-specific settings
 T3_DB_TYPE=$(autocomplete "$T3_DB_TYPE" mariadb postgresql)
 case "$T3_DB_TYPE" in
@@ -809,7 +820,7 @@ case "$CMD" in
 
     run)
         # Roll back if command fails or is interrupted
-        trap "{ set +x +e; } 2>/dev/null; echo '*** Command failed or interrupted, rolling back ***'; $0 stop -e '$T3_ENGINE' -n '$T3_NAME' --rm; exit 1" ERR SIGINT
+        trap "{ set +x +e; } 2>/dev/null; echo $'\n*** Command failed or interrupted, rolling back ***'; $0 stop -e '$T3_ENGINE' -n '$T3_NAME' --rm; exit 1" ERR SIGINT
 
         # Database container required?
         if [ -z "$T3_DB_TYPE" ]; then
@@ -821,6 +832,7 @@ case "$CMD" in
                 --hostname "$T3_HOSTNAME" \
                 --volume "$T3_ROOT:$T3_ROOTDIR" \
                 --publish $T3_PORT:80 \
+                $ENV_OPTIONS \
                 $HOST_IP_OPTION \
                 $REMOVE_OPTION \
                 $@ \
@@ -848,6 +860,7 @@ case "$CMD" in
                 --name "$T3_NAME" \
                 --network container:"${T3_NAME}-db" \
                 --volume "$T3_ROOT:$T3_ROOTDIR" \
+                $ENV_OPTIONS \
                 $HOST_IP_OPTION \
                 $REMOVE_OPTION \
                 $@ \
@@ -904,7 +917,7 @@ case "$CMD" in
 
     unmount)
         test -d "$DIR_PATH" || usage "Option '--unmount' is required"
-        sudo --prompt 'sudo authorization is required for unmounting: ' \
+        sudo --prompt 'sudo authorization is required for unmounting a working directory: ' \
             umount "$DIR_PATH" \
         && echo "Working directory '$DIR_PATH' unmounted from volume '$(basename "$DIR_PATH")'"    
         ;;
