Fix: allow deleting COMPOSER_EXCLUDEd directories

diff --git a/files/usr/local/bin/composer b/files/usr/local/bin/composer
--- a/files/usr/local/bin/composer
+++ b/files/usr/local/bin/composer
@@ -3,12 +3,8 @@
 #
 # Runs Composer as user $APACHE_USER and in working directory $TYPO3_ROOT.
 #
-# Beforehand, all directories listed in $COMPOSER_EXCLUDE_FILE are bind-mounted
-# somewehere else so that modifications in these directories do not appear at
-# the host in the volume mapped to $TYPO3_ROOT.
-#
-# Afterwards, these directories are unmounted, thus restoring their content
-# from the host.
+# Beforehand, all directories listed in $COMPOSER_EXCLUDE_FILE are copied to
+# temporary directories. Afterwards, these directories are restored.
 #
 
 . /etc/environment
@@ -18,23 +14,21 @@ RUN_COMPOSER=1
 if [ -f $COMPOSER_EXCLUDE_FILE ] && [ -n "$(cat $COMPOSER_EXCLUDE_FILE)" ]; then
     COMPOSER_EXCLUDE_ROOT=$APACHE_HOME/composer-exclude
 
-    # Sub-mount empty directories over the protected directories, 
-    # making sure that each sub-mounted directory is unmounted afterwards
+    # Copy directories to exclude, making sure that each one is restored afterwards
     set -e
     TRAP_CMDS=
 
     while IFS=':' read -ra DIRS; do
         for D in "${DIRS[@]}"; do
-            if [ -n "$D" -a -d $TYPO3_ROOT/$D ]; then
-                mkdir -p $COMPOSER_EXCLUDE_ROOT/$D
-                chown $APACHE_USER: $COMPOSER_EXCLUDE_ROOT/$D
-                mount --bind $COMPOSER_EXCLUDE_ROOT/$D $TYPO3_ROOT/$D
-                echo "Excluding $D"
-                TRAP_CMDS="umount $TYPO3_ROOT/$D && rm -rf $COMPOSER_EXCLUDE_ROOT/$D && echo 'Restored '$D; $TRAP_CMDS"
+            if [ -n "$D" -aq -d $TYPO3_ROOT/$D ]; then
+                SAVE_DIR=$(mktemp -d)
+                rsync -aq $TYPO3_ROOT/$D/ $SAVE_DIR/
+                echo "Excluded $D"
+                TRAP_CMDS="rm -rf $TYPO3_ROOT/$D/"'*'"; rsync -aq $SAVE_DIR/ $TYPO3_ROOT/$D/ && echo 'Restored '$D; $TRAP_CMDS"
                 trap "set +e; $TRAP_CMDS" EXIT
 
             else
-                echo "Not excluding $D: no such directory in $TYPO3_ROOT" 1>&2
+                echo "Cannot exclude $D: no such directory in $TYPO3_ROOT" 1>&2
                 RUN_COMPOSER=
             fi
         done
